image: maven:3.6-jdk-11

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    --file app/pom.xml

cache:
    key: "$CI_JOB_NAME"
    paths:
        - .m2/repository

stages:
  - build
  - security
  - sca_scan
  - scan

build-job:
  stage: build
  script:
      - 'mvn $MAVEN_CLI_OPTS clean package'
      - ls -al app/target
      - chmod +x app/target
  artifacts:
      name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_build
      paths:
          - app/target
      expire_in: 1 week

pipeline-scan:
  stage: security
  dependencies:
    - build-job
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_pipeline-results
    paths:
      - results.json
    expire_in: 1 week
    when: always
  script:
    - curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - unzip pipeline-scan-LATEST.zip pipeline-scan.jar
    - java -jar pipeline-scan.jar
      --veracode_api_id "${VERACODE_API_ID}"
      --veracode_api_key "${VERACODE_API_SECRET}"
      --file app/target/verademo*.war
      --fail_on_severity="Very High, High"
      --fail_on_cwe="80"
      --timeout "${CI_TIMEOUT}"
      --project_name "${CI_PROJECT_PATH}"
      --project_url "${CI_REPOSITORY_URL}"
      --project_ref "${CI_COMMIT_REF_NAME}"
      --gl_issue_generation true
      --gl_vulnerability_generation true
      --issue_details true
      --summary_output true || true
    - false || exit_code=$?
    - if [ $exit_code -ne 0 ]; then echo "Pipeline scan found " + $exit_code " issues"; fi;

sca-scan:
  stage: sca_scan
  script:
      - cd app
      - export SRCCLR_SCM_NAME=$CI_PROJECT_PATH
      - export SRCCLR_SCM_URI=$CI_PROJECT_URL
      - export SRCCLR_SCM_REF=$(if [ "$CI_COMMIT_TAG" == "" ]; then echo $CI_COMMIT_REF_NAME; else echo $CI_COMMIT_TAG; fi);
      - export SRCCLR_SCM_REF_TYPE=$(if [ "$CI_COMMIT_TAG" == "" ]; then echo "branch"; else echo "tag"; fi);
      - export SRCCLR_SCM_REV=$CI_COMMIT_SHA
      - curl -sSL https://download.sourceclear.com/ci.sh | sh
  allow_failure: true

veracode-policy-scan:
  stage: scan
  dependencies:
    - build-job
  image: veracode/api-wrapper-java:latest
  only:
      - main
  script:
      - java -jar /opt/veracode/api-wrapper.jar
        -vid ${VERACODE_API_ID}
        -vkey ${VERACODE_API_SECRET}
        -action UploadAndScan
        -appname "${CI_PROJECT_NAME}"
        -createprofile true
        -autoscan true
        -filepath app/target/*.war
        -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
